#!/usr/bin/bash

SAVE_DIR="/home/sycasec/.local/share/Steam/steamapps/compatdata/367520/pfx/drive_c/users/steamuser/AppData/LocalLow/Team Cherry/Hollow Knight"

SAVE_DIR_EL="/home/sycasec/.local/share/Steam/steamapps/compatdata/1245620/pfx/drive_c/users/steamuser/AppData/Roaming/EldenRing/76561198119515987/"
TARGET_DIR="${HOME}/Documents/HKsaves"

if [[ $1 == "save" ]]; then
	cp -v "$SAVE_DIR"/*.dat ${TARGET_DIR}
elif [[ $1 == "load" ]]; then
	cp -f ${TARGET_DIR}/*.dat "$SAVE_DIR"/
else
	echo "invalid argument: \"save\" and \"load\" only."
fi
