#!/usr/bin/bash

PATH="$HOME/.config/bspwm/scripts:$PATH"
theme_dir="$HOME/.config/bspwm/sycasec"

## fix java applications
export _JAVA_AWT_WM_NONREPARENTING=1

INTERNAL_MONITOR="eDP-1-1"
EXTERNAL_MONITOR="HDMI-1-1"

if [[ $(xrandr -q | grep 'HDMI-1-1 connected') ]]; then
	xrandr --output eDP-1-1 --mode 1920x1080 --rotate normal --output HDMI-1-1 --mode 1920x1080 --rotate normal --rate 120.00 --primary --left-of eDP-1-1 &
	bspc monitor $EXTERNAL_MONITOR -d '1' '2' '3' '4' '5' '6'
	bspc monitor $INTERNAL_MONITOR -d '7' '8' '9' '10' '11' '12'
else
	bspc monitor $INTERNAL_MONITOR -d '1' '2' '3' '4' '5' '6'
fi

#
# workspaces() {
# 	name=1
# 	for monitor in $(bspc query -M); do
# 		bspc monitor "${monitor}" -n "$name" -d '1' '2' '3' '4' '5' '6'
# 		#bspc monitor ${monitor} -n "$name" -d '' '' '' '' '' ''
# 		(( name++ ))
# 	done
# }
'7' '8' '9' '10' '11' '12'

# workspaces

bspc config external_rules_command $HOME/.config/bspwm/scripts/ExternalRules

bspc config split_ratio 0.51
bspc config single_monocle true
bspc config borderless_monocle false
bspc config gapless_monocle false

bspc config focus_follows_pointer true
bspc config pointer_follows_focus false
bspc config pointer_motion_interval 5
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

. SetSysVars

processes=("picom" "polybar" "eww" "sxhkd" "dunst")

for process in "${processes[@]}"; do
	if pidof -q "$process"; then
		pkill -9 -x "$process" >/dev/null
		sleep 0.1
	fi
done

. ${theme_dir}/Theme.sh

picom --config "$HOME"/.config/bspwm/picom.conf &

# Launch dunst notification daemon
dunst -config "$HOME"/.config/bspwm/dunstrc &

# Reload sxhkd daemon
sxhkd -c "$HOME"/.config/bspwm/sxhkdrc &

nm-applet &

optimus-manager-qt &

# set wall paper
feh -z --no-fehbg --bg-fill $HOME/Downloads/walls/

# Fix cursor
xsetroot -cursor_name left_ptr
