#!/bin/sh
# Script by Swindles McCoop
# https://git.cbps.xyz/swindlesmccoop/not-just-dotfiles/src/branch/master/.local/bin/swallow
# I changed the name because i like consume more. swallow sounds kinda sexual.

# Hide terminal windows while opening another program
# Example usage: consume mpv myvideo.mkv
# Aliases can be created to make this easier

COMMAND="$*"
BINARY="$(printf "$COMMAND" | sed 's/ .*//')"
ARGS="$(printf "$COMMAND" | sed "s/$BINARY //")"

main() {
	WINID=$(xdo id)
	xdo hide $WINID
	$BINARY "$ARGS" || $BINARY $ARGS
	xdo show $WINID
}

[ "$1" = "" ] && printf "Error: You must provide at least one argument.\nExample usage: consume mpv ~/videos/AmericanPsycho.mkv\n" || main "$@"
